# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\"\n\x10InferenceRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"%\n\x11InferenceResponse\x12\x10\n\x08response\x18\x01 \x01(\t2Z\n\x10InferenceService\x12\x46\n\tInference\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseB\x1eZ\x1cgrpc-llm-service/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\034grpc-llm-service/proto;proto'
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=64
  _globals['_INFERENCERESPONSE']._serialized_start=66
  _globals['_INFERENCERESPONSE']._serialized_end=103
  _globals['_INFERENCESERVICE']._serialized_start=105
  _globals['_INFERENCESERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
